// Characters
export const ADD_CHARACTER_TO_LIST = 'ADD_CHARACTER_TO_LIST'

export const SET_CURRENT_CHARACTER = 'SET_CURRENT_CHARACTER'
export const SET_CHARACTER_PROFILE = 'SET_CHARACTER_PROFILE'
export const SET_CHARACTER_WORLD = 'SET_CHARACTER_WORLD'
export const SET_CHARACTER_MOVIES = 'SET_CHARACTER_MOVIES'
export const SET_CHARACTER_VEHICLES = 'SET_CHARACTER_VEHICLES'

export const SET_LOADING = 'SET_LOADING'
export const STOP_LOADING = 'STOP_LOADING' 
export const CLEAN_UP_CHARACTER_DATA = 'CLEAN_UP_CHARACTER_DATA'


// Auth
export const SET_USER_DATA = 'SET_USER_DATA'
export const REMOVE_USER_DATA = 'REMOVE_USER_DATA'


// Liked list 
export const ADD_TO_LIKED_LIST = 'ADD_TO_LIKED_LIST'
export const REMOVE_FROM_LIKED_LIST = 'REMOVE_FROM_LIKED_LIST'
export const CLEAN_UP_LIKED_STATUS = 'CLEAN_UP_LIKED_STATUS'




